### PR TITLE
fix: don't populate data.remote_state_consumer_ids if global

### LINKED ISSUE #407: possible memory leak introduced in 0.27.0
We are seeing an unstable spike in memory utilization with 0.27.0 release during workspace plans.  It does not happen in the previous release(s).  I will open a support case as well but wanted to mention here.

### PR DESCRIPTION
**Pull request by brandonc**
## Description

The memory leak described in #407 is actually a workspace data source bug where we always fetch all remote_state_consumer_ids, even if the workspace data source is global. The API happily enumerates all other workspaces in this case. If you have many pages of workspaces, this could take a very long time to plan.

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See TESTS.md to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TFE_TOKEN="$(tfc_local_token)" TFE_HOSTNAME="$(tfc_local_hostname)" TF_ACC=1 go test ./... -v -tags=integration -run TestAccTFEWorkspaceDataSource
?   	github.com/hashicorp/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFEWorkspaceDataSource_remoteStateConsumers
--- PASS: TestAccTFEWorkspaceDataSource_remoteStateConsumers (38.45s)
=== RUN   TestAccTFEWorkspaceDataSource_basic
--- PASS: TestAccTFEWorkspaceDataSource_basic (35.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-tfe/tfe	76.658s
?   	github.com/hashicorp/terraform-provider-tfe/version	[no test files]
```

Fixes #407

### CODE REVIEW

File: tfe/data_source_workspace.go [hunk 1]
```diff
@@ -193,6 +185,27 @@ func dataSourceTFEWorkspaceRead(d *schema.ResourceData, meta interface{}) error
...
 	d.Set("working_directory", workspace.WorkingDirectory)
 
+	// Set remote_state_consumer_ids if global_remote_state is false
+	globalRemoteState := workspace.GlobalRemoteState
+	if globalRemoteState {
+		if err := d.Set("remote_state_consumer_ids", []string{}); err != nil {
+			return err
+		}
+	} else {
+		compatibleGlobalRemoteState, remoteStateConsumerIDs, err := readWorkspaceStateConsumers(workspace.ID, tfeClient)
```
Comment (chrisarcand) [inline tfe/data_source_workspace.go:195]: The name `compatibleGlobalRemoteState` didn't really tell me what this value is, and I had to stare at `readWorkspaceStateConsumers` for a long time to understand it.

Ignoring the fact that the function should probably have godoc on it explaining the return value (😅 That's my bad), how about something like `legacyGlobalState` or `oldTFE` or something to indicate that `true` == "This is an old version of TFE and for all points and purposes uses global state" ?

**Review by chrisarcand — COMMENTED** [review]
Code looks good to me!

I don't have time this morning sadly, but someone should smoke test this change before approving; this is a finicky part of the provider.

Nice work!

File: tfe/data_source_workspace.go [hunk 2]
```diff
@@ -193,6 +185,27 @@ func dataSourceTFEWorkspaceRead(d *schema.ResourceData, meta interface{}) error
...
 	d.Set("working_directory", workspace.WorkingDirectory)
 
+	// Set remote_state_consumer_ids if global_remote_state is false
+	globalRemoteState := workspace.GlobalRemoteState
+	if globalRemoteState {
+		if err := d.Set("remote_state_consumer_ids", []string{}); err != nil {
+			return err
+		}
+	} else {
+		legacyGlobalState, remoteStateConsumerIDs, err := readWorkspaceStateConsumers(workspace.ID, tfeClient)
```
Comment (sebasslash) [inline tfe/data_source_workspace.go:195]: Really minor cleanup suggestion: since `readWorkspaceStateConsumers()` returns a bool in a tuple, and if that value is true we set `globalRemoteState = true`, couldn't we just assign that function's return value to `globalRemoteState` instead?

**Review by sebasslash — APPROVED** [review]

File: tfe/data_source_workspace.go (hunk 2 above)
Comment (brandonc) [reply tfe/data_source_workspace.go:195]: I didn't want to do that until I determined whether err != nil

Comment (brandonc) [reply tfe/data_source_workspace.go:195]: I kind of like it the way it is because it names the return value as a legacy compatibility issue
