### PR TITLE
fix: invalid include value when reading workspace

### LINKED ISSUE #1786: Error reading workspace over `tfe_workspace_settings` with `0.68.0`
#### Terraform Enterprise version

Terraform Enterprise v202409-3

#### Terraform version

```plaintext
1.11.4
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace_settings" "default" {
  workspace_id        = ***
  agent_pool_id       = ***
  execution_mode      = ***
  global_remote_state = ***
}
```

#### Debug Output

```plaintext

```

#### Actual Behavior

Getting below error with `0.68.0` and everything ok with `~> 0.67.0`
Image

### PR DESCRIPTION
**Pull request by brandonc**
## Description

There was a new bug in the latest release against some versions of Terraform Enterprise that do not allow this include value. Other read methods utilize a fallback in this scenario, so I added it here.

Fixes #1786 

_Remember to:_

- [x] _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md)_
- [x] _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md#updating-the-documentation)_

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspaceSettings" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspaceSettings -timeout 15m
=== RUN   TestAccTFEWorkspaceSettings_basic
2025/07/21 11:56:16 [DEBUG] Configuring client for host "tfcdev-xxx.ngrok.app"
2025/07/21 11:56:16 [DEBUG] Service discovery for tfcdev-xxxx.ngrok.app at https://tfcdev-xxx.ngrok.app/.well-known/terraform.json
--- PASS: TestAccTFEWorkspaceSettings_basic (13.51s)
=== RUN   TestAccTFEWorkspaceSettings_stateSharing
--- PASS: TestAccTFEWorkspaceSettings_stateSharing (8.43s)
=== RUN   TestAccTFEWorkspaceSettings_basicOptions
--- PASS: TestAccTFEWorkspaceSettings_basicOptions (10.09s)
=== RUN   TestAccTFEWorkspaceSettingsRemoteState
--- PASS: TestAccTFEWorkspaceSettingsRemoteState (9.27s)
=== RUN   TestAccTFEWorkspaceSettings_import
--- PASS: TestAccTFEWorkspaceSettings_import (7.23s)
=== RUN   TestAccTFEWorkspaceSettings_importByName
--- PASS: TestAccTFEWorkspaceSettings_importByName (7.09s)
=== RUN   TestAccTFEWorkspaceSettings_basicTags
--- PASS: TestAccTFEWorkspaceSettings_basicTags (19.68s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   75.932s
```

### CODE REVIEW

File: internal/provider/resource_tfe_workspace_settings.go [hunk 1]
```diff
@@ -461,17 +461,25 @@ func (r *workspaceSettings) Read(ctx context.Context, req resource.ReadRequest,
 }
 
 func (r *workspaceSettings) readSettings(ctx context.Context, workspaceID string) (*modelWorkspaceSettings, error) {
+	log.Printf("[DEBUG] Read configuration of workspace: %s", workspaceID)
```
Comment (ctrombley) [inline internal/provider/resource_tfe_workspace_settings.go:464]: I've seen `tflog.Debug(...)` instead elsewhere around the codebase. Do we prefer one over the other?

**Comment by brandonc** [comment]
debug log from smoke test

```
tfe_workspace.this: Refreshing state... [id=ws-GPT4f3hVDfnewvEj]
2025-07-21T14:28:48.242-0600 [DEBUG] provider.terraform-provider-tfe: [DEBUG] Read configuration of workspace: ws-GPT4f3hVDfnewvEj
2025-07-21T14:28:48.403-0600 [DEBUG] provider.terraform-provider-tfe: [DEBUG] Workspace ws-GPT4f3hVDfnewvEj read failed due to unsupported Include; retrying without it
```
