### PR TITLE
Use the stages attribute for the Workspace Run Task resource

### LINKED ISSUE #1456: tfe_workspace_run_task apply fails when using stages argument and TFE v202408-1
We are getting an error when using the new "stages' argument on the resource tfe_workspace_run_task.

```hcl

resource "tfe_workspace_run_task" "vm_agent" {
  task_id      = tfe_organization_run_task.default.id
  workspace_id = var.workspace_id
  stages = [
    "post_plan",
    "pre_plan",
  ]
  enforcement_level = "advisory"
}
```

#### Terraform Enterprise version
v202408-1

#### Terraform version

```plaintext
1.3.8
```

#### TFE Provider version
```plaintext
0.58.1
```

#### Debug Output

```plaintext
tfe_workspace_run_task.vm_agent, provider "provider[\\\"registry.terraform.io/hashicorp/tfe\\\"]" produced an unexpected new value: .stages: element 1 has vanished.\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}
Operation failed: failed running terraform apply (exit 1)
```

#### Expected Behavior
Should have applied without errors

#### Actual Behavior
Error

```
When applying changes to tfe_workspace_run_task.vm_agent, provider "provider[\"registry.terraform.io/hashicorp/tfe\"]" produced an unexpected new value: .stages: element 1 has vanished.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### PR DESCRIPTION
**Pull request by glennsarti**
Fixes #1456

## Description

Previously the schema for workspace run tasks was updated for the new stages
property however it wasn't actually used. This commit updates the Workspace
Run Task resource to aware of the stages attributes. In particular;

* Attempts to detect if the remote service supports the stages property. Stages
is available in HCP Terraform and TFE v202404-1 onwards.

* Munges the Stages and Stage attribtue depending on the remote capability.

* Emits a warning about the remove server capability.

* Adds some automated tests. Unfortunately we can't test older TFE versions,
to ensure the munging is correct, however manual testing was performed in
a local development enivronment to confirm the behaviour.

* Removes the default value for the Stage property in the Schema. This will
not cause issues with existing state and allows the provider to determine
if the attribute was passed in via configuration as opposed to defaulting.

- [x] _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md)_
- [x] _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md#updating-the-documentation)_

## Testing plan

Apart from CI

1. Use a version of TFE
1. Apply configuration which uses the `stages` property with multiple values

## External links

- [API documentation](https://github.com/hashicorp/terraform-provider-tfe/pull/1330)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/1330)

## Output from acceptance tests

Tests can be run in CI

### CODE REVIEW

File: internal/provider/client_capabilites_test.go [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+	return r.tfeVer
+}
+
+func (r *staticCapabilityResolver) SetIsCloud(val bool) {
+	r.isCloud = val
+}
+
+func (r *staticCapabilityResolver) SetRemoteTFEVersion(val string) {
+	r.tfeVer = val
+}
```
Comment (cam-stitt) [inline internal/provider/client_capabilites_test.go:25]: Is there a reason for setters over exported fields?

File: internal/provider/resource_tfe_workspace_run_task.go [hunk 2]
```diff
@@ -297,3 +320,84 @@ func (r *resourceWorkspaceRunTask) UpgradeState(ctx context.Context) map[int64]r
 		},
 	}
 }
+
+func (r *resourceWorkspaceRunTask) supportsStagesProperty() bool {
+	// The Stages property is available in HCP Terraform and Terraform Enterprise v202404-1 onwards.
+	//
+	// The version comparison here can use plain string comparisons due to the nature of the naming scheme. If
+	// TFE every changes its scheme, the comparison will be problematic.
+	return r.capabilities.IsCloud() || r.capabilities.RemoteTFEVersion() > "v202404"
```
Comment (cam-stitt) [inline internal/provider/resource_tfe_workspace_run_task.go:329]: Probably worth placing the static version into a global SupportedStagesPropertyVersion variable

File: internal/provider/resource_tfe_workspace_run_task.go [hunk 3]
```diff
@@ -297,3 +320,84 @@ func (r *resourceWorkspaceRunTask) UpgradeState(ctx context.Context) map[int64]r
...
+	summary := "Terraform Enterprise version"
+	detail := fmt.Sprintf("The version of Terraform Enterprise does not support the stages attribute on Workspace Run Tasks. Got %s but requires v202404-1+", r.config.Client.RemoteTFEVersion())
+	if isError {
+		d.AddError(detail, summary)
+	} else {
+		d.AddWarning(detail, summary)
+	}
+}
+
+func (r *resourceWorkspaceRunTask) extractStageAndStages(plan modelTFEWorkspaceRunTaskV1, d *diag.Diagnostics) (*tfe.Stage, *[]tfe.Stage) {
```
Comment (cam-stitt) [inline internal/provider/resource_tfe_workspace_run_task.go:342]: Are we certain we want a pointer to a slice? A slice can have the value `nil` if you were wanting to validate if a value was returned.

**Review by cam-stitt — CHANGES_REQUESTED** [review]

File: internal/provider/client_capabilites_test.go (hunk 1 above)
Comment (glennsarti) [reply internal/provider/client_capabilites_test.go:25]: Not really no.  Apart from the names I chose which would shadow the interface methods

File: internal/provider/resource_tfe_workspace_run_task.go (hunk 3 above)
Comment (glennsarti) [reply internal/provider/resource_tfe_workspace_run_task.go:342]: Whoops, yeah I forgot about that... I can change that

File: internal/provider/resource_tfe_workspace_run_task.go (hunk 2 above)
Comment (glennsarti) [reply internal/provider/resource_tfe_workspace_run_task.go:329]: will do

File: internal/provider/client_capabilites_test.go (hunk 1 above)
Comment (cam-stitt) [reply internal/provider/client_capabilites_test.go:25]: True, carry on.

File: internal/provider/resource_tfe_workspace_run_task.go (hunk 3 above)
Comment (glennsarti) [reply internal/provider/resource_tfe_workspace_run_task.go]: Done

File: internal/provider/resource_tfe_workspace_run_task.go (hunk 2 above)
Comment (glennsarti) [reply internal/provider/resource_tfe_workspace_run_task.go]: Done

**Review by cam-stitt — APPROVED** [review]
